CREATE TABLE ΣΜ (id SERIAL NOT NULL, ΣΜ int4, Έτος int4, Ταυτότητα varchar(10), "Ανωτ Υ" char(255), "Κατωτ Υ" char(255), Β int4, Α int4, Ν int4, Δ int4, "Αντίστοιχη με" char(8), "Σύγχρονη με" char(8), Κάτω char(8), Πάνω char(8), Μήκος float4, Πλάτος float4, Διάμετρ float4, Βάθος float4, Ύψος float4, Πάχος float4, "Λίθος Κείμενο" varchar(255), "Πλίνθος Κείμενο" varchar(255), "Κεραμοπλαστικός διάοσμος" varchar(255), Spolia varchar(255), Ξύλο varchar(255), "Μεγεθος στοιχείων" varchar(255), "Αριθμ. σωζ δομών" varchar(255), "Πειγραφή/ερμηνεία" varchar(255), "Χαρακτ. σε σχ. με ΣΜ" varchar(255), "Σχέσεις με ΣΜ" varchar(255), Κόσκινο bool, Νεροκόσκινο bool, "Κόσκινο Ποσοστό" int4, "Νεροκόσκινο Ποσοστό" int4, "Ποσότητα κεραμικής" varchar(255), Ημερολόγιο int4, ΣκαρίφημαPath varchar(255), ΦώτοPath varchar(255), ΚάτοψηPath varchar(255), ΌψηPath varchar(255), Συντάκτης varchar(255), Ημερομηνία date, "Επίχρισμα(είδος)id" int4 NOT NULL, "Χρονολόγηση μέχριid" int4 NOT NULL, "Χρονολόγηση αποid" int4 NOT NULL, Συνθήκεςid int4 NOT NULL, Θέσηid int4 NOT NULL, "Συνδετικό υλικόid" int4 NOT NULL, Χρώμαid int4 NOT NULL, "Κατηγορία/τύποςid" int4 NOT NULL, "Επιλογές Λίθουid" int4 NOT NULL, "Δομή/Υφήid" int4 NOT NULL, ΤύποςΣΜid int4 NOT NULL, "Πιθανότητα επιμίξεωνid" int4 NOT NULL, "Επίχρισμα (χρώμα)id" int4 NOT NULL, "Κλίση προςid" int4 NOT NULL, Δάπεδοid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE "Κατηγορία/τύπος" (id SERIAL NOT NULL, Selections varchar(50) UNIQUE, PRIMARY KEY (id));
CREATE TABLE Υλικό (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Δομή/Υφή" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE Χρώμα (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE Θέση (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Χρονολόγηση απο" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Χρονολόγηση μέχρι" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE Βάσει (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Ανασκαφ. τεχνική" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE Συνθήκες (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Πιθανότητα επιμίξεων" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Έχει Υλικό" (ΣΜid int4 NOT NULL, Υλικόid int4 NOT NULL, PRIMARY KEY (ΣΜid, Υλικόid));
CREATE TABLE "Έχει Βάσει" (ΣΜid int4 NOT NULL, Βάσειid int4 NOT NULL, PRIMARY KEY (ΣΜid, Βάσειid));
CREATE TABLE "Έχει Ανασκαφ. τεχνική" (ΣΜid int4 NOT NULL, "Ανασκαφ. τεχνικήid" int4 NOT NULL, PRIMARY KEY (ΣΜid, "Ανασκαφ. τεχνικήid"));
CREATE TABLE "Έχει Σκελετό" (ΣΜid int4 NOT NULL, ΣκελετόςId int4 NOT NULL, PRIMARY KEY (ΣΜid, ΣκελετόςId));
CREATE TABLE Σκελετός (id SERIAL NOT NULL, "ΣΜ κοψίματος" int4, Έτος int4, Τομέας int4, Κατασκευή varchar(6), Ενότητα varchar(255), Σύνολο varchar(255), Φάση varchar(255), Ταυτότητα varchar(255), "Κάτω/πριν από" varchar(255), "Πάνω/μετά από" varchar(255), Β int4, Ν int4, Α int4, Δ int4, "Ανωτ. Υ κραν" int4, "Κατώτ Υ. κραν." int4, Πλάτος float4, Βάθος float4, Προσανατολισμός varchar(255), "Γενική στάση σώματος" varchar(255), Κεφάλι varchar(255), Μήκος float4, Κορμός varchar(255), "Δεξί χέρι" varchar(255), "Αριστερό χέρι" varchar(255), "Δεξί πόδι" varchar(255), "Αριστερό πόδι" varchar(255), "Περιγραφή/σχόλια" varchar(255), "Υ. σκελετού κατά χώραν" int4, "Μήκ. μηριαίου οστού" int4, Συνευρήματα varchar(255), "Ανασκ. τεχνική" varchar(255), Συνθήκες varchar(255), ΣκαρίφημαPath varchar(255), ΦώτοPath varchar(255), ΣχέδιοPath varchar(255), Ημερολόγιο int4, Συντάκτης varchar(255), Ημερομηνία date, "Τύπος Ταφήςid" int4 NOT NULL, "Τύπος τάφουid" int4 NOT NULL, Οστάid int4 NOT NULL, Ταφήid int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE "Τύπος Ταφής" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Τύπος τάφου" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE Οστά (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE Ταφή (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Κλίση προς" (id SERIAL NOT NULL, Selections varchar(50) UNIQUE, PRIMARY KEY (id));
CREATE TABLE ΤύποςΣΜ (id SERIAL NOT NULL, Selections char(100) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Επιλογές Λίθου" (id SERIAL NOT NULL, Selections varchar(100) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Συνδετικό υλικό" (id SERIAL NOT NULL, Selections varchar(50) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Επίχρισμα(είδος)" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Έχει Τοιχοποιία" (ΣΜid int4 NOT NULL, Τοιχοποιίαid int4 NOT NULL, PRIMARY KEY (ΣΜid, Τοιχοποιίαid));
CREATE TABLE Τοιχοποιία (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Έχει Προσμίξεις" (Προσμίξειςid int4 NOT NULL, ΣΜid int4 NOT NULL, PRIMARY KEY (Προσμίξειςid, ΣΜid));
CREATE TABLE Προσμίξεις (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE "Επίχρισμα (χρώμα)" (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
CREATE TABLE Δάπεδο (id SERIAL NOT NULL, Selections varchar(255) UNIQUE, PRIMARY KEY (id));
ALTER TABLE "Έχει Υλικό" ADD CONSTRAINT "FKΈχει Υλικό559163" FOREIGN KEY (ΣΜid) REFERENCES ΣΜ (id);
ALTER TABLE "Έχει Υλικό" ADD CONSTRAINT "FKΈχει Υλικό269372" FOREIGN KEY (Υλικόid) REFERENCES Υλικό (id);
ALTER TABLE "Έχει Βάσει" ADD CONSTRAINT "FKΈχει Βάσει308191" FOREIGN KEY (Βάσειid) REFERENCES Βάσει (id);
ALTER TABLE "Έχει Ανασκαφ. τεχνική" ADD CONSTRAINT "FKΈχει Ανασκ454241" FOREIGN KEY (ΣΜid) REFERENCES ΣΜ (id);
ALTER TABLE "Έχει Ανασκαφ. τεχνική" ADD CONSTRAINT "FKΈχει Ανασκ796372" FOREIGN KEY ("Ανασκαφ. τεχνικήid") REFERENCES "Ανασκαφ. τεχνική" (id);
ALTER TABLE "Έχει Σκελετό" ADD CONSTRAINT "FKΈχει Σκελε987498" FOREIGN KEY (ΣΜid) REFERENCES ΣΜ (id);
ALTER TABLE "Έχει Σκελετό" ADD CONSTRAINT "FKΈχει Σκελε879757" FOREIGN KEY (ΣκελετόςId) REFERENCES Σκελετός (id);
ALTER TABLE "Έχει Τοιχοποιία" ADD CONSTRAINT "FKΈχει Τοιχο574269" FOREIGN KEY (ΣΜid) REFERENCES ΣΜ (id);
ALTER TABLE "Έχει Βάσει" ADD CONSTRAINT "FKΈχει Βάσει574817" FOREIGN KEY (ΣΜid) REFERENCES ΣΜ (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ397278 FOREIGN KEY ("Επίχρισμα(είδος)id") REFERENCES "Επίχρισμα(είδος)" (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ540376 FOREIGN KEY ("Χρονολόγηση μέχριid") REFERENCES "Χρονολόγηση μέχρι" (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ848861 FOREIGN KEY ("Χρονολόγηση αποid") REFERENCES "Χρονολόγηση απο" (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ155110 FOREIGN KEY (Συνθήκεςid) REFERENCES Συνθήκες (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ31865 FOREIGN KEY (Θέσηid) REFERENCES Θέση (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ288479 FOREIGN KEY ("Συνδετικό υλικόid") REFERENCES "Συνδετικό υλικό" (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ118974 FOREIGN KEY (Χρώμαid) REFERENCES Χρώμα (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ239272 FOREIGN KEY ("Κατηγορία/τύποςid") REFERENCES "Κατηγορία/τύπος" (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ952874 FOREIGN KEY ("Επιλογές Λίθουid") REFERENCES "Επιλογές Λίθου" (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ282831 FOREIGN KEY ("Δομή/Υφήid") REFERENCES "Δομή/Υφή" (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ118314 FOREIGN KEY (ΤύποςΣΜid) REFERENCES ΤύποςΣΜ (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ76080 FOREIGN KEY ("Πιθανότητα επιμίξεωνid") REFERENCES "Πιθανότητα επιμίξεων" (id);
ALTER TABLE "Έχει Προσμίξεις" ADD CONSTRAINT "FKΈχει Προσμ397956" FOREIGN KEY (Προσμίξειςid) REFERENCES Προσμίξεις (id);
ALTER TABLE "Έχει Προσμίξεις" ADD CONSTRAINT "FKΈχει Προσμ170122" FOREIGN KEY (ΣΜid) REFERENCES ΣΜ (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ725323 FOREIGN KEY ("Επίχρισμα (χρώμα)id") REFERENCES "Επίχρισμα (χρώμα)" (id);
ALTER TABLE Σκελετός ADD CONSTRAINT FKΣκελετός979261 FOREIGN KEY ("Τύπος Ταφήςid") REFERENCES "Τύπος Ταφής" (id);
ALTER TABLE Σκελετός ADD CONSTRAINT FKΣκελετός105093 FOREIGN KEY ("Τύπος τάφουid") REFERENCES "Τύπος τάφου" (id);
ALTER TABLE Σκελετός ADD CONSTRAINT FKΣκελετός806318 FOREIGN KEY (Οστάid) REFERENCES Οστά (id);
ALTER TABLE Σκελετός ADD CONSTRAINT FKΣκελετός90590 FOREIGN KEY (Ταφήid) REFERENCES Ταφή (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ302605 FOREIGN KEY ("Κλίση προςid") REFERENCES "Κλίση προς" (id);
ALTER TABLE ΣΜ ADD CONSTRAINT FKΣΜ777887 FOREIGN KEY (Δάπεδοid) REFERENCES Δάπεδο (id);
ALTER TABLE "Έχει Τοιχοποιία" ADD CONSTRAINT "FKΈχει Τοιχο425134" FOREIGN KEY (Τοιχοποιίαid) REFERENCES Τοιχοποιία (id);
